repos:
  # Autoformat: Bash scripts
  - repo: https://github.com/lovesegfault/beautysh
    rev: 6.0.1
    hooks:
      - id: beautysh

  # Autoformat: markdown, javacsript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args:
          - "--trailing-comma=es5"
          - "--print-width=100"

