language: node_js
branches:
  except:
    - /^greenkeeper.*/
# Test against Long Term Support (LTS) releases in a "current", "active", and
# "maintenance" status: https://nodejs.org/en/about/releases/
node_js:
  - 14
  - 12
  - 10
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - travis_retry npm test
after_success:
  - npm run codecov
