# Useful GitHub Actions docs:
#
# - https://help.github.com/en/actions
# - https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# - https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish.yml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  # Job to run linter / autoformat
  lint:
    runs-on: ubuntu-20.04
    steps:
      # Action Repo: https://github.com/actions/checkout
      - name: "Checkout repo"
        uses: actions/checkout@v2

      # Action Repo: https://github.com/actions/setup-node
      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      # Action Repo: https://github.com/actions/cache
      - name: "Cache node_modules"
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: "Install"
        run: |
          npm ci

      # Run the pre-commit action
      # Repo: https://github.com/pre-commit/action
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

      - name: npm audit
        run: |
          # If this fails, run `npm audit fix`
          npm audit --production --audit-level=moderate

  test:
    runs-on: ubuntu-20.04
    # - https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false # Do not cancel all jobs if one fails
      matrix:
        # IMPORTANT: Make sure to update package.json's engines.node field to
        #            always require at least the oldest version, as well as our
        #            README.md file under the install section.
        node_version:
          # Removing node 10 is dropping support for ubuntu 20.04 LTS
          - "10"
          - "12"
          - "14"
          - "16"
          - "17"

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      # Action Repo: https://github.com/actions/setup-node
      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      # Action Repo: https://github.com/actions/cache
      - name: "Cache node_modules"
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Run tests"
        run: |
          npm test

      # Action Repo: https://github.com/codecov/codecov-action
      - name: "Upload coverage to codecov"
        uses: codecov/codecov-action@v1
